### ISSUE TITLE
Proposal: Show tags on the main catalog page for use as filters

### ISSUE THREAD

**Issue by MoralCode** [wilsonmcdade/tunnelvision#27]
It would be awesome to have a list of all the tags on the site (possibly under the search box) so that they can act as a kind of filter if people arent sure what to search for

As a bonus, being able to do logical filtering with the tags (i.e. ANY vs ALL selected tags) would be helpful too

**Comment by wilsonmcdade** [comment]
This would be cool! Some filtering options would be great. I think being able to pick from a range of years could be cool too.

**Comment by wilsonmcdade** [comment]
#32
